In [1]:
import pandas as pd

In [4]:
data1 = pd.read_csv("dates_on_left_stock_data.csv")

In [5]:
data1

,Date,AAPL_PctChange,AAPL_Price,ABT_PctChange,ABT_Price,ADBE_PctChange,ADBE_Price,ADP_PctChange,ADP_Price,AMAT_PctChange,...,V_PctChange,V_Price,WBA_PctChange,WBA_Price,WMT_PctChange,WMT_Price,XOM_PctChange,XOM_Price,ZM_PctChange,ZM_Price
0,11/21/2023,NaN,189.71,NaN,99.92,NaN,610.99,NaN,226.04,NaN,...,NaN,250.32,NaN,19.39,NaN,51.26,NaN,101.01,NaN,65.94
1,11/22/2023,0.35,190.38,0.78,100.69,1.43,619.72,-0.03,225.99,0.37,...,0.59,251.80,-1.38,19.13,-0.76,50.87,-0.43,100.58,-3.20,63.83
2,11/24/2023,-0.70,189.04,0.17,100.86,-0.05,619.43,-0.21,225.51,0.58,...,0.23,252.37,0.77,19.27,0.90,51.33,0.54,101.12,1.10,64.53
3,11/27/2023,-0.09,188.86,-0.16,100.70,-0.03,619.27,-0.65,224.04,0.31,...,-0.06,252.21,-3.55,18.59,0.45,51.56,-0.58,100.53,1.58,65.55
4,11/28/2023,0.32,189.47,-0.63,100.06,0.65,623.32,-0.07,223.87,-1.82,...,-0.47,251.02,-0.65,18.47,1.19,52.18,-0.06,100.47,3.02,67.53
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
247,11/14/2024,1.38,228.22,-0.61,115.03,-0.49,529.87,-1.79,301.99,1.76,...,-0.40,308.25,-2.44,8.55,-1.20,84.47,0.07,120.56,-2.83,82.63
248,11/15/2024,-1.41,225.00,0.76,115.90,-5.00,503.37,-1.44,297.64,-9.20,...,0.45,309.64,-3.75,8.23,-0.26,84.25,-1.04,119.31,-1.80,81.14
249,11/18/2024,1.34,228.02,1.26,117.36,-0.77,499.51,0.08,297.89,1.10,...,0.81,312.16,5.22,8.66,-0.20,84.08,0.84,120.31,-2.72,78.93
250,11/19/2024,0.11,228.28,-0.20,117.13,0.02,499.61,-0.12,297.54,-0.83,...,-0.10,311.85,-4.27,8.29,3.00,86.60,-1.40,118.63,-1.49,77.75
251,11/20/2024,0.32,229.00,-1.02,115.93,-0.02,499.50,0.35,298.59,0.70,...,-1.43,307.39,-0.60,8.24,0.67,87.18,1.42,120.32,1.43,78.86

In [9]:
data2 = pd.read_csv("new_label.csv")
data2

,Ticker,Title,Date,Excerpt,Summary,PctChange,Price,Label
0,AMZN,Direxion Daily AMZN Bull 1.5X Shares (NASDAQ:A...,11/29/2023,Direxion Daily AMZN Bull 1.5X Shares (NASDAQ:A...,Direxion Daily AMZN Bull 1.5X Shares (NASDAQ:A...,-0.48,146.32,0
1,AMZN,Direxion Daily AMZN Bear 1X Shares (NASDAQ:AMZ...,11/30/2023,Direxion Daily AMZN Bear 1X Shares (NASDAQ:AMZ...,Direxion Daily AMZN Bear 1X Shares (\nNASDAQ:A...,-0.16,146.09,0
2,AMZN,iRobot surges 37% on report of EU approval for...,11/24/2023,iRobot stock soars as EU reportedly set to app...,iRobot (NASDAQ:IRBT) skyrocketed 37% on a repo...,0.02,146.74,0
3,AMZN,Direxion Daily AMZN Bear 1X Shares (NASDAQ:AMZ...,11/29/2023,Direxion Daily AMZN Bear 1X Shares (NASDAQ:AMZ...,Direxion Daily AMZN Bear 1X Shares (\nNASDAQ:A...,-0.48,146.32,0
4,AMZN,Direxion Daily AMZN Bear 1X Shares (NASDAQ:AMZ...,11/28/2023,Direxion Daily AMZN Bear 1X Shares (NASDAQ:AMZ...,Direxion Daily AMZN Bear 1X Shares (\nNASDAQ:A...,-0.47,147.03,0
...,...,...,...,...,...,...,...,...
72834,ROST,Capitol art captures views of Missouri a centu...,10/07/2024,The building's art reflects the images Missour...,Lightning flashed over the Missouri Capitol on...,-3.75,140.12,4
72835,ROST,Capitol art captures views of Missouri a centu...,10/07/2024,Lightning flashed over the Missouri Capitol on...,A statue representing the Missouri River as th...,-3.75,140.12,4
72836,ROST,"1,567 Shares in Ross Stores, Inc. (NASDAQ:ROST...",10/10/2024,Fulton Bank N.A. bought a new position in shar...,Fulton Bank N.A. bought a new position in shar...,-0.96,141.03,0
72837,ROST,Will Nintendo's Holiday 2024 lineup send the S...,10/07/2024,Hands-on with Nintendo's big holiday releases,Anticipation for Nintendo's next console has r...,-3.75,140.12,4
72838,ROST,TimesSquare U.S. Mid Cap Growth Strategy Q3 20...,10/10/2024,TimesSquare U.S. Mid Cap Growth Strategy under...,TimesSquare Capital Management Global markets ...,-0.96,141.03,0

In [10]:
data3 = pd.read_csv("news_all_merged_file.csv")
data3

,Ticker,Title,Date,excerpt,summary
0,AMZN,"AMZN stock: Key news, insider trading, valuati...",11/21/2023,Get the latest on AMZN stock. Dive into up-to-...,Real-time price chart of AMZN stock\n\nStay up...
1,AMZN,Direxion Daily AMZN Bull 1.5X Shares (NASDAQ:A...,11/29/2023,Direxion Daily AMZN Bull 1.5X Shares (NASDAQ:A...,Direxion Daily AMZN Bull 1.5X Shares (NASDAQ:A...
2,AMZN,Amazon is a multi-trillion dollar giant. Oppen...,03/12/2023,Amazon (AMZN) remains a top large-cap pick for...,Amazon (NASDAQ:AMZN)'s market cap has surpasse...
3,AMZN,Direxion Daily AMZN Bull 1.5X Shares (NASDAQ:A...,11/11/2023,Direxion Daily AMZN Bull 1.5X Shares (NASDAQ:A...,Direxion Daily AMZN Bull 1.5X Shares (\nNASDAQ...
4,AMZN,Amazon.com Inc. (AMZN) Stock: A Guide to the M...,08/12/2023,The stock of Amazon.com Inc. (AMZN) has gone d...,The stock of Amazon.com Inc. (AMZN) has gone d...
...,...,...,...,...,...
88829,ROST,"1,567 Shares in Ross Stores, Inc. (NASDAQ:ROST...",10/10/2024,Fulton Bank N.A. bought a new position in shar...,Fulton Bank N.A. bought a new position in shar...
88830,ROST,Instant Reaction: Seattle Seahawks fall flat i...,10/06/2024,The voices of Seattle Sports weigh in on the S...,After opening the season with three straight w...
88831,ROST,"Ross Stores, Inc. (NASDAQ:ROST) Shares Acquire...",10/06/2024,Handelsbanken Fonder AB raised its position in...,Handelsbanken Fonder AB raised its position in...
88832,ROST,Will Nintendo's Holiday 2024 lineup send the S...,10/07/2024,Hands-on with Nintendo's big holiday releases,Anticipation for Nintendo's next console has r...
88833,ROST,TimesSquare U.S. Mid Cap Growth Strategy Q3 20...,10/10/2024,TimesSquare U.S. Mid Cap Growth Strategy under...,TimesSquare Capital Management Global markets ...

In [11]:
data4 = pd.read_csv("news_all_sentiment.csv")
data4

,Ticker,Title,Date,excerpt,summary,Processed Title,Processed Excerpt,Processed Summary,Title Sentiment Score,Excerpt Sentiment Score,Summary Sentiment Score
0,AMZN,"AMZN stock: Key news, insider trading, valuati...",11/21/2023,Get the latest on AMZN stock. Dive into up-to-...,Real-time price chart of AMZN stock\n\nStay up...,amzn stock key news insider trading valuation ...,get latest amzn stock dive uptodate amazoncom ...,realtime price chart amzn stock stay uptodate ...,0.0000,0.2960,0.9973
1,AMZN,Direxion Daily AMZN Bull 1.5X Shares (NASDAQ:A...,11/29/2023,Direxion Daily AMZN Bull 1.5X Shares (NASDAQ:A...,Direxion Daily AMZN Bull 1.5X Shares (NASDAQ:A...,direxion daily amzn bull x share nasdaqamzu sh...,direxion daily amzn bull x share nasdaqamzu ge...,direxion daily amzn bull x share nasdaqamzu ge...,0.6369,0.9647,0.9984
2,AMZN,Amazon is a multi-trillion dollar giant. Oppen...,03/12/2023,Amazon (AMZN) remains a top large-cap pick for...,Amazon (NASDAQ:AMZN)'s market cap has surpasse...,amazon multitrillion dollar giant oppenheimer ...,amazon amzn remains top largecap pick oppenhei...,amazon nasdaqamzns market cap surpassed trilli...,0.1779,0.4939,0.9963
3,AMZN,Direxion Daily AMZN Bull 1.5X Shares (NASDAQ:A...,11/11/2023,Direxion Daily AMZN Bull 1.5X Shares (NASDAQ:A...,Direxion Daily AMZN Bull 1.5X Shares (\nNASDAQ...,direxion daily amzn bull x share nasdaqamzu se...,direxion daily amzn bull x share nasdaqamzu ge...,direxion daily amzn bull x share nasdaqamzu ge...,0.7783,0.9313,0.9970
4,AMZN,Amazon.com Inc. (AMZN) Stock: A Guide to the M...,08/12/2023,The stock of Amazon.com Inc. (AMZN) has gone d...,The stock of Amazon.com Inc. (AMZN) has gone d...,amazoncom inc amzn stock guide market trend,stock amazoncom inc amzn gone week rise past m...,stock amazoncom inc amzn gone week rise past m...,0.0000,0.0000,0.9885
...,...,...,...,...,...,...,...,...,...,...,...
88829,ROST,"1,567 Shares in Ross Stores, Inc. (NASDAQ:ROST...",10/10/2024,Fulton Bank N.A. bought a new position in shar...,Fulton Bank N.A. bought a new position in shar...,share ross store inc nasdaqrost bought fulton ...,fulton bank na bought new position share ross ...,fulton bank na bought new position share ross ...,0.2960,0.8625,0.9978
88830,ROST,Instant Reaction: Seattle Seahawks fall flat i...,10/06/2024,The voices of Seattle Sports weigh in on the S...,After opening the season with three straight w...,instant reaction seattle seahawks fall flat lo...,voice seattle sport weigh seahawks loss new yo...,opening season three straight win seattle seah...,-0.3182,-0.3182,0.4800
88831,ROST,"Ross Stores, Inc. (NASDAQ:ROST) Shares Acquire...",10/06/2024,Handelsbanken Fonder AB raised its position in...,Handelsbanken Fonder AB raised its position in...,ross store inc nasdaqrost share acquired hande...,handelsbanken fonder ab raised position share ...,handelsbanken fonder ab raised position share ...,0.2960,0.8834,0.9986
88832,ROST,Will Nintendo's Holiday 2024 lineup send the S...,10/07/2024,Hands-on with Nintendo's big holiday releases,Anticipation for Nintendo's next console has r...,nintendos holiday lineup send switch right,handson nintendos big holiday release,anticipation nintendos next console reached fe...,0.4019,0.4019,0.9999
88833,ROST,TimesSquare U.S. Mid Cap Growth Strategy Q3 20...,10/10/2024,TimesSquare U.S. Mid Cap Growth Strategy under...,TimesSquare Capital Management Global markets ...,timessquare u mid cap growth strategy q commen...,timessquare u mid cap growth strategy underper...,timessquare capital management global market p...,0.3818,0.6369,0.9999

In [12]:
data5 = pd.read_csv("news_with_textblob_sentiments.csv")
data5

,Ticker,Title,Date,Excerpt,Summary,Title Sentiment Score,Excerpt Sentiment Score,Summary Sentiment Score
0,AMZN,"AMZN stock: Key news, insider trading, valuati...",11/21/2023,Get the latest on AMZN stock. Dive into up-to-...,Real-time price chart of AMZN stock\n\nStay up...,0.000000,0.500000,0.133939
1,AMZN,Direxion Daily AMZN Bull 1.5X Shares (NASDAQ:A...,11/29/2023,Direxion Daily AMZN Bull 1.5X Shares (NASDAQ:A...,Direxion Daily AMZN Bull 1.5X Shares (NASDAQ:A...,0.000000,0.078125,0.039002
2,AMZN,Amazon is a multi-trillion dollar giant. Oppen...,03/12/23,Amazon (AMZN) remains a top large-cap pick for...,Amazon (NASDAQ:AMZN)'s market cap has surpasse...,0.000000,0.500000,0.055935
3,AMZN,Direxion Daily AMZN Bull 1.5X Shares (NASDAQ:A...,11/11/23,Direxion Daily AMZN Bull 1.5X Shares (NASDAQ:A...,Direxion Daily AMZN Bull 1.5X Shares (\nNASDAQ...,0.071429,0.155000,0.040103
4,AMZN,Amazon.com Inc. (AMZN) Stock: A Guide to the M...,08/12/23,The stock of Amazon.com Inc. (AMZN) has gone d...,The stock of Amazon.com Inc. (AMZN) has gone d...,0.000000,-0.218519,0.007290
...,...,...,...,...,...,...,...,...
89021,ROST,"1,567 Shares in Ross Stores, Inc. (NASDAQ:ROST...",10/10/24,Fulton Bank N.A. bought a new position in shar...,Fulton Bank N.A. bought a new position in shar...,0.000000,0.001623,0.048767
89022,ROST,Instant Reaction: Seattle Seahawks fall flat i...,10/06/24,The voices of Seattle Sports weigh in on the S...,After opening the season with three straight w...,-0.012500,0.136364,0.083281
89023,ROST,"Ross Stores, Inc. (NASDAQ:ROST) Shares Acquire...",10/06/24,Handelsbanken Fonder AB raised its position in...,Handelsbanken Fonder AB raised its position in...,0.000000,0.140000,0.041307
89024,ROST,Will Nintendo's Holiday 2024 lineup send the S...,10/07/24,Hands-on with Nintendo's big holiday releases,Anticipation for Nintendo's next console has r...,0.285714,0.000000,0.159651
89025,ROST,TimesSquare U.S. Mid Cap Growth Strategy Q3 20...,10/10/24,TimesSquare U.S. Mid Cap Growth Strategy under...,TimesSquare Capital Management Global markets ...,0.000000,0.116667,0.071491